
server:
 port: 8080


spring:
 mvc:
   view:
     prefix: /WEB-INF/views/
     suffix: .jsp
      
 datasource:
   driver-class-name: org.mariadb.jdbc.Driver
   username: green
<<<<<<< HEAD
   password: green1234
   url: jdbc:mariadb://localhost:3306/cosdb?serverTimezone=Asia/Seoul
=======
   password: 1234
   url: jdbc:mariadb://localhost:3306/greendb?serverTimezone=Asia/Seoul
>>>>>>> master
      
 jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # create, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true   




